In [1]:
'''Q1. Create a 5x5 NumPy array of integers from 0 to 24. 

Extract the second row and third column using indexing. 

Replace all odd numbers with -1 using broadcasting. '''

import numpy as np

arr = np.arange(0, 25).reshape(5,5)
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [2]:
a = arr[1,2]
a

7

In [3]:
odd_numbers = arr == (arr % 2 != 0)

arr[odd_numbers] = -1
arr

array([[-1, -1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
'''
Q2. Generate a 3D NumPy array of shape (2, 3, 4) filled with random integers between 10 and 50. 

Use slicing to extract the last 2 elements from each inner-most array. 

Broadcast a scalar value (e.g., subtract 10 from all elements). 
'''

'\nQ2. Generate a 3D NumPy array of shape (2, 3, 4) filled with random integers between 10 and 50. \n\nUse slicing to extract the last 2 elements from each inner-most array. \n\nBroadcast a scalar value (e.g., subtract 10 from all elements). \n'

In [6]:
#Generate a 3D NumPy array of shape (2, 3, 4) filled with random integers between 10 and 50.
array = np.random.randint(10, 51, size=(2, 3, 4))
array


array([[[16, 32, 16, 28],
        [47, 22, 48, 11],
        [40, 26, 30, 34]],

       [[18, 24, 13, 45],
        [11, 50, 24, 48],
        [49, 38, 46, 34]]])

In [8]:
#Use slicing to extract the last 2 elements from each inner-most array. 
array[:, :, -2:]

array([[[16, 28],
        [48, 11],
        [30, 34]],

       [[13, 45],
        [24, 48],
        [46, 34]]])

In [11]:
#Broadcast a scalar value (e.g., subtract 10 from all elements). 
arr2 = array-5
arr2

array([[[11, 27, 11, 23],
        [42, 17, 43,  6],
        [35, 21, 25, 29]],

       [[13, 19,  8, 40],
        [ 6, 45, 19, 43],
        [44, 33, 41, 29]]])